products = [
    {"name": "laptop", "price": 800, "quantity": 4},
    {"name": "mouse", "price": 40, "quantity": 10},
    {"name": "monitor", "price": 400, "quantity": 3},
    {"name": "keyboard", "price": 80, "quantity": 5},
    {"name": "microphone", "price": 100, "quantity": 2},
    {"name": "camera", "price": 200, "quantity": 1},
    {"name": "headphone", "price": 50, "quantity": 5},
    {"name": "speaker", "price": 100, "quantity": 3},
    {"name": "printer", "price": 300, "quantity": 2},
    {"name": "scanner", "price": 200, "quantity": 1},
    {"name": "projector", "price": 500, "quantity": 1},
    {"name": "router", "price": 100, "quantity": 2},
    {"name": "switch", "price": 200, "quantity": 1},
    {"name": "server", "price": 1000, "quantity": 1},
    {"name": "UPS", "price": 200, "quantity": 1},
    {"name": "tablet", "price": 300, "quantity": 2},
    {"name": "smartphone", "price": 500, "quantity": 1},
    {"name": "smartwatch", "price": 200, "quantity": 1},
    {"name": "smartband", "price": 100, "quantity": 2},
    {"name": "earphone", "price": 50, "quantity": 5},
    {"name": "powerbank", "price": 100, "quantity": 3},
    {"name": "charger", "price": 50, "quantity": 5},
    {"name": "cable", "price": 20, "quantity": 10},
    
]